name: Java CI with Gradle (Kotlin DSL)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: '21'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Checkstyle
      run: ./gradlew checkstyleMain checkstyleTest

    - name: Run tests
      run: ./gradlew test

    - name: Test Coverage Report
      run: |
        ./gradlew jacocoTestReport
        ./cc-test-reporter after-build --exit-code $?
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
